# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 14);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20131206152142");
user_pref("browser.slowStartup.averageTime", 3598);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage", "chrome://lspnr/content/home.html");
user_pref("browser.startup.homepage_override.buildID", "20131206152142");
user_pref("browser.startup.homepage_override.mstone", "26.0");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1392102530214");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAccepted", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1392298551360");
user_pref("datareporting.policy.dataSubmissionPolicyResponseTime", "1392298569361");
user_pref("datareporting.policy.dataSubmissionPolicyResponseType", "accepted-info-bar-dismissed");
user_pref("datareporting.policy.firstRunTime", "1392016130213");
user_pref("datareporting.sessions.current.activeTicks", 6);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 1247);
user_pref("datareporting.sessions.current.main", 161);
user_pref("datareporting.sessions.current.sessionRestored", 1446);
user_pref("datareporting.sessions.current.startTime", "1392385512275");
user_pref("datareporting.sessions.current.totalTime", 61);
user_pref("datareporting.sessions.currentIndex", 15);
user_pref("datareporting.sessions.previous.0", "{\"s\":1392016129074,\"a\":6,\"t\":41,\"c\":true,\"m\":60,\"fp\":3669,\"sr\":5368}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1392016173256,\"a\":3,\"t\":17,\"c\":true,\"m\":1948,\"fp\":3674,\"sr\":3928}");
user_pref("datareporting.sessions.previous.10", "{\"s\":1392261814433,\"a\":4,\"t\":19,\"c\":true,\"m\":490,\"fp\":1465,\"sr\":1630}");
user_pref("datareporting.sessions.previous.11", "{\"s\":1392264656050,\"a\":4,\"t\":83,\"c\":true,\"m\":41,\"fp\":1257,\"sr\":1476}");
user_pref("datareporting.sessions.previous.12", "{\"s\":1392292101326,\"a\":7,\"t\":61,\"c\":true,\"m\":1461,\"fp\":4617,\"sr\":4920}");
user_pref("datareporting.sessions.previous.13", "{\"s\":1392298488201,\"a\":11,\"t\":118,\"c\":true,\"m\":471,\"fp\":1779,\"sr\":1995}");
user_pref("datareporting.sessions.previous.14", "{\"s\":1392384801431,\"a\":5,\"t\":65,\"c\":true,\"m\":2110,\"fp\":5672,\"sr\":5943}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1392016196545,\"a\":1,\"t\":3,\"c\":true,\"m\":41,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1392017689140,\"a\":12,\"t\":61,\"c\":true,\"m\":1540,\"fp\":3475,\"sr\":3753}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1392019291374,\"a\":4,\"t\":21,\"c\":true,\"m\":1513,\"fp\":3635,\"sr\":3815}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1392022826785,\"a\":2,\"t\":21,\"c\":true,\"m\":1559,\"fp\":3863,\"sr\":4062}");
user_pref("datareporting.sessions.previous.6", "{\"s\":1392115639390,\"a\":2,\"t\":22,\"c\":true,\"m\":1921,\"fp\":7496,\"sr\":7895}");
user_pref("datareporting.sessions.previous.7", "{\"s\":1392116426425,\"a\":3,\"t\":25,\"c\":true,\"m\":41,\"fp\":1459,\"sr\":1317}");
user_pref("datareporting.sessions.previous.8", "{\"s\":1392117065742,\"a\":5,\"t\":31,\"c\":true,\"m\":41,\"fp\":1129,\"sr\":1309}");
user_pref("datareporting.sessions.previous.9", "{\"s\":1392261033994,\"a\":3,\"t\":24,\"c\":true,\"m\":1161,\"fp\":4434,\"sr\":4666}");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"langpack-ru@firefox.mozilla.org\":{\"version\":\"26.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-ru@firefox.mozilla.org.xpi\"}}");
user_pref("extensions.databaseSchema", 15);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:2.7,lspnr%40lspnr:!,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:26.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installCache", "[{\"name\":\"app-system-share\",\"addons\":{\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"mtime\":1387111389000,\"rdfTime\":1375741724000}}},{\"name\":\"app-global\",\"addons\":{\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1375570715000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1387111299000,\"rdfTime\":1386345194000},\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1375570715000},\"langpack-ru@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-ru@firefox.mozilla.org.xpi\",\"mtime\":1386346258000}}},{\"name\":\"app-profile\",\"addons\":{\"lspnr@lspnr\":{\"descriptor\":\"/home/adam/DevRepos/stegabank/ddir/firefox/FF-profile/extensions/lspnr@lspnr\",\"mtime\":1392264069000,\"rdfTime\":1392016062000}}}]");
user_pref("extensions.lastAppVersion", "26.0");
user_pref("extensions.lastPlatformVersion", "26.0");
user_pref("extensions.lspnr.first_run", false);
user_pref("extensions.pendingOperations", false);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", false);
user_pref("gecko.buildID", "20131206152142");
user_pref("gecko.mstone", "26.0");
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.proxy.http", "127.0.0.1");
user_pref("network.proxy.http_port", 8079);
user_pref("network.proxy.ssl", "127.0.0.1");
user_pref("network.proxy.ssl_port", 8079);
user_pref("network.proxy.type", 1);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 51475);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("toolkit.startup.last_success", 1392385512);
user_pref("toolkit.telemetry.previousBuildID", "20131206152142");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1394608135);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
